# Generated by Django 4.2.1 on 2023-05-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.CharField(max_length=100, null=True)),
                ('nume', models.CharField(max_length=100, null=True)),
                ('nume_complet', models.CharField(max_length=100, null=True)),
                ('catedra', models.CharField(blank=True, choices=[('Matematica', 'MATEMATICA'), ('Lb Romana', 'LIMBA SI LITERATURA ROMANA SI LIMBA LATINA'), ('Chimie', 'CHIMIE'), ('Fizica', 'FIZICA'), ('Limba Engleza', 'LIMBA ENGLEZA'), ('Limba Germana', 'LIMBA GERMANA'), ('Limba Franceza', 'LIMBA FRANCEZA'), ('Geografie', 'GEOGRAFIE'), ('Informatica', 'INFORMATICA SI TEHNOLOGIA INFORMATIEI'), ('Biologie', 'BIOLOGIE'), ('Istorie', 'ISTORIE'), ('Ed Fizica', 'EDUCATIE FIZICA'), ('Socio Umane', 'DISCIPLINE SOCIO-UMANE'), ('Religie', 'RELIGIE'), ('ED_P_M_T', 'EDUCATIE PLASTICA, MUZICALA SI TEHNOLOGICA')], default=None, max_length=50)),
                ('titulatura', models.CharField(choices=[('Grad 1', 'Grad 1'), ('Grad 2', 'Grad 2'), ('Grad 3', 'Grad 3'), ('Debutant', 'Debutant'), ('Definitiv', 'Definitiv')], default='Grad 1', max_length=20)),
                ('doctor', models.BooleanField(default=False)),
                ('sef_catedra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proiecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblema', models.ImageField(null=True, upload_to='')),
                ('titlu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(upload_to='frontend/public/assests/poze_proiecte/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proiecte')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitlu', models.CharField(max_length=255)),
                ('paragraf', models.TextField(max_length=2000)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proiecte')),
            ],
        ),
    ]
