# Generated by Django 4.2.1 on 2023-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proiecte_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proiecte',
            name='tip',
            field=models.CharField(choices=[('Proiect școlar', 'Proiect școlar'), ('Activități extrașcolare', 'Activități extrașcolare')], default='Proiect școlar', max_length=30),
        ),
    ]
