# Generated by Django 4.2.1 on 2023-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proiecte_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=2000)),
                ('ecuson', models.ImageField(upload_to='poze_anunturi/')),
            ],
        ),
        migrations.AlterField(
            model_name='poze',
            name='poza',
            field=models.ImageField(upload_to='poze_proiecte/'),
        ),
        migrations.AlterField(
            model_name='profesori',
            name='catedra',
            field=models.CharField(blank=True, choices=[('Matematica', 'MATEMATICA'), ('Lb_Romana', 'LIMBA SI LITERATURA ROMANA SI LIMBA LATINA'), ('Chimie', 'CHIMIE'), ('Fizica', 'FIZICA'), ('Limba_Engleza', 'LIMBA ENGLEZA'), ('Limba_Germana', 'LIMBA GERMANA'), ('Limba_Franceza', 'LIMBA FRANCEZA'), ('Geografie', 'GEOGRAFIE'), ('Informatica', 'INFORMATICA SI TEHNOLOGIA INFORMATIEI'), ('Biologie', 'BIOLOGIE'), ('Istorie', 'ISTORIE'), ('Ed_Fizica', 'EDUCATIE FIZICA'), ('Socio_Umane', 'DISCIPLINE SOCIO-UMANE'), ('Religie', 'RELIGIE'), ('ED_P_M_T', 'EDUCATIE PLASTICA, MUZICALA SI TEHNOLOGICA')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='proiecte',
            name='emblema',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proiecte',
            name='tip',
            field=models.CharField(choices=[('Pagini', 'Pagini'), ('Proiect școlar', 'Proiect școlar'), ('Activități extrașcolare', 'Activități extrașcolare')], default='Proiect școlar', max_length=30),
        ),
    ]
