# Generated by Django 4.2.1 on 2023-05-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anunturi_alter_poze_poza_alter_profesori_catedra_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anunturi',
        ),
    ]
