# Generated by Django 4.2.1 on 2023-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anunturi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='ecuson',
            field=models.ImageField(blank=True, upload_to='poze_anunturi/'),
        ),
    ]
