# Generated by Django 4.2.1 on 2023-05-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_anunturi_ecuson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anunturi',
        ),
    ]
