# Generated by Django 4.2.1 on 2023-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_anunturi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
