# Generated by Django 4.2.1 on 2023-05-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_anunturi_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anunturi',
        ),
    ]
