# Generated by Django 4.2.1 on 2023-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_data_anunturi_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='data_created',
            field=models.DateField(auto_now=True),
        ),
    ]
