# Generated by Django 4.2.1 on 2023-05-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_anunturi_data_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anunturi',
        ),
    ]
