# Generated by Django 4.2.1 on 2023-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_anunturi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=2000)),
                ('data_delete', models.DateTimeField(blank=True)),
                ('data_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
