# Generated by Django 4.2.1 on 2023-05-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_anunturi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='data_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
