# Generated by Django 4.2.1 on 2023-05-25 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_anunturi_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
