# Generated by Django 4.2.1 on 2023-05-25 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_anunturi_data_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olimpici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('anul', models.IntegerField()),
                ('premiul', models.CharField(max_length=255)),
                ('concursul', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='anunturi',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
