# Generated by Django 4.2.1 on 2023-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_olimpici_alter_anunturi_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpici',
            name='poza',
            field=models.ImageField(blank=True, upload_to='poze_olimpici/'),
        ),
    ]
