# Generated by Django 4.2.1 on 2023-05-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_programari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programari',
        ),
    ]
