# Generated by Django 4.2.1 on 2023-05-25 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_programari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programari',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddConstraint(
            model_name='programari',
            constraint=models.UniqueConstraint(fields=('data', 'sala'), name='unique_time_location'),
        ),
    ]
