# Generated by Django 4.2.1 on 2023-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_programari_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizare_Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diriginte', models.CharField(max_length=255)),
                ('clasa', models.CharField(choices=[('Pregătitoare', 'Pregătitoare'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=255)),
                ('litera', models.CharField(max_length=15)),
                ('nr_elevi', models.IntegerField()),
            ],
        ),
    ]
