# Generated by Django 4.2.1 on 2023-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_organizare_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizare_clase',
            name='nr_elevi',
            field=models.CharField(max_length=255),
        ),
    ]
