# Generated by Django 4.2.1 on 2023-06-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_organizare_clase_nr_elevi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizare_clase',
            name='clasa',
            field=models.CharField(choices=[('Preg.', 'Preg.'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=255),
        ),
    ]
