# Generated by Django 4.2.1 on 2023-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_nr_elevi_organizare_clase_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesori',
            name='titulatura',
            field=models.CharField(choices=[('grad 1', 'grad 1'), ('grad 2', 'grad 2'), ('grad 3', 'grad 3'), ('Debutant', 'Debutant'), ('Definitiv', 'Definitiv')], default='grad 1', max_length=20),
        ),
    ]
