# Generated by Django 4.2.1 on 2023-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_profesori_titulatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poze',
            name='poza',
            field=models.ImageField(upload_to='poze_proiecte/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
