# Generated by Django 4.2.1 on 2023-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_poze_poza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poze',
            name='poza',
            field=models.ImageField(upload_to='poze_proiecte/<function proiect at 0x00000229A004FEB0>'),
        ),
    ]
