# Generated by Django 4.2.1 on 2023-06-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_poze_poza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documente_proiecte/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proiecte')),
            ],
        ),
    ]
