# Generated by Django 4.2.1 on 2023-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_data_delete_anunturi_data_stergere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='data_stergere',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
