# Generated by Django 4.2.1 on 2023-07-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_consiliu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consiliu',
        ),
    ]
