# Generated by Django 4.2.1 on 2023-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_delete_consiliu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consiliu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('functie', models.CharField(max_length=255)),
                ('tip', models.CharField(choices=[('Consiliu administrativ', 'Consiliu administrativ'), ('Consiliu elevilor', 'Consiliu elevilor')], max_length=255)),
            ],
        ),
    ]
