# Generated by Django 4.2.1 on 2023-07-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_anunturi_tip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programari',
        ),
    ]
