# Generated by Django 4.2.1 on 2023-07-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_delete_programari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_administrativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persoane_administrativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('functie', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proiecte')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_administrativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proiecte')),
            ],
        ),
    ]
