# Generated by Django 4.2.1 on 2023-07-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_personal_administrativ_persoane_administrativ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_administrativ',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personal_administrativ'),
        ),
        migrations.AlterField(
            model_name='persoane_administrativ',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personal_administrativ'),
        ),
    ]
