# Generated by Django 4.2.1 on 2023-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_olimpici_anul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consiliul_elevilor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('poza', models.ImageField(blank=True, upload_to='poze_consiliu/')),
                ('functie', models.CharField(max_length=255)),
                ('nr_telefon', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
            ],
        ),
    ]
