# Generated by Django 4.2.1 on 2023-08-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_consiliul_elevilor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proiecte',
            name='tip',
            field=models.CharField(choices=[('Pagini', 'Pagini'), ('Proiect școlar', 'Proiect școlar'), ('Activități extrașcolare', 'Activități extrașcolare'), ('Proiect consiliul elevilor', 'Proiect consiliul elevilor')], default='Proiect școlar', max_length=30),
        ),
    ]
