# Generated by Django 4.2.1 on 2023-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_proiecte_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=500)),
            ],
        ),
    ]
