# Generated by Django 4.2.1 on 2023-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_proiecte_facebook_proiecte_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documente',
            name='nume',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
