# Generated by Django 4.2.1 on 2023-08-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_documente_nume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documente',
            name='nume',
            field=models.CharField(default='Document', max_length=255),
        ),
    ]
