# Generated by Django 4.2.1 on 2023-08-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_documente_nume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunturi_documente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documente_anunturi/')),
                ('nume', models.CharField(default='Document', max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anunturi')),
            ],
        ),
    ]
