# Generated by Django 4.2.1 on 2023-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_anunturi_documente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poze',
            name='poza',
            field=models.FileField(upload_to='poze_proiecte/'),
        ),
    ]
