# Generated by Django 4.2.1 on 2023-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_consiliul_elevilor_nr_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consiliul_elevilor',
            name='nume',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consiliul_elevilor',
            name='poza',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='poze_consiliu/'),
        ),
    ]
