# Generated by Django 4.2.1 on 2023-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_consiliul_elevilor_nume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consiliul_elevilor',
            name='nume',
            field=models.CharField(max_length=255),
        ),
    ]
